-- DDL CRIANDO TABELA PARA EXERCÍCIOS
CREATE TABLE FUNCIONARIOS 
(
	ID int identity(1, 1),
	NOME VARCHAR(50) NOT NULL,
	SALARIO DECIMAL(10, 2),
	SETOR VARCHAR(30)
	)
 

-- DML INSERT
	INSERT INTO FUNCIONARIOS VALUES ('João', 1000, ''), ('José', 2000, ''), ('Alexandre', 3000, '')

-- OU
	INSERT INTO FUNCIONARIOS (NOME, SALARIO) VALUES ('Pedro', 1000)

-- DML UPDATE
	UPDATE FUNCIONARIOS SET SALARIO = '1500'
	WHERE ID = '1'
-- OU AUMENTO DE  50% SOBRE SALÁRIO ATUAL
	UPDATE FUNCIONARIOS SET SALARIO = SALARIO*1.5
	WHERE ID = '1'

SELECT * FROM FUNCIONARIOS

UPDATE FUNCIONARIOS SET SALARIO = SALARIO*1.5, SETOR = 'TI'
WHERE ID != '1'

-- DML DELETE
DELETE FUNCIONARIOS WHERE ID = '1'

-- DDL CRIANDO TABELA
CREATE TABLE FUNCIONARIO 
(
	MATRICULA INT IDENTITY(1,1),
	NOME CHAR(50) NOT NULL,
	SOBRENOME CHAR(50) NOT NULL,
	ENDERECO CHAR(50),
	CIDADE CHAR(50),
	PAIS CHAR(50),
	DATA_NASC DATETIME 
)

--DDL CRIANDO TABELA COM CHAVE ESTRANGEIRA 
CREATE TABLE SALARIO
(
	MATRICULA INT PRIMARY KEY NOT NULL,
	SALARIO DECIMAL(10,2) NOT NULL,
	FOREIGN KEY(MATRICULA) REFERENCES FUNCIONARIO(MATRICULA)
)

-- CORRIGINDO ERRO NA TAB FUNCIONARIO
-- DDL ADICIONAR CHAVE PRIMÁRIA NA TABELA FUNCIONÁRIO
ALTER TABLE FUNCIONARIO ADD PRIMARY KEY (MATRICULA) 

-- DDL CRIAÇÃO DE TABELA COM CHAVE PRIMÁRIA
CREATE TABLE audit_salario
	(
	transacao INT IDENTITY(1,1),
	matricula INT NOT NULL,
	data_trans DATETIME NOT NULL,
	sal_antigo DECIMAL(10,2),
	sal_novo DECIMAL(10,2),
	Usuario VARCHAR(20) NOT NULL
	)

-- DDL CRIACAO DE INDEX
CREATE INDEX ix_func1 ON funcionario(data_nasc)
CREATE INDEX ix_func2 ON funcionario(cidade, pais)

--Adicionando novo campo na tabela
ALTER TABLE FUNCIONARIO ADD GENERO CHAR(1)

SELECT *  FROM FUNCIONARIO

-- RENOMEANDO CAMPO DA TABELA
-- EXEC sp_rename 'TABELA_ORIGEM.CAMPO_ORIGEM', 'Campo_orig', 'COLUMN'
EXEC Sp_rename 'funcionario.endereco', 'ender', 'COLUMN'

--ALTERANDO TIPO DA COLUNA
USE curso
ALTER TABLE FUNCIONARIO ALTER COLUMN ENDER VARCHAR(30)

--EXCLUINDO CAMPO DA COLUNA 
ALTER TABLE FUNCIONARIO DROP COLUMN GENERO

