--VIEWS
--AS VIEWS NOS PERMITEM CRIAR UM CÓDIGO MAIS LIMPO, NA MEDIDA EM QUE PODEM CONTER UM SELECT COMPLEXO.

--CRIANDO UMA VIEW
USE AdventureWorks2014
CREATE VIEW V_DATA_CONTRATACAO
AS 
	 SELECT P.FIRSTNAME,
	 P.LASTNAME,
	 E.BUSINESSENTITYID,
	 E.HIREDATE
	 FROM HumanResources.Employee E
	 JOIN Person.Person AS P
ON E.BusinessEntityID = P.BusinessEntityID

--SELECT NA VIEW 

SELECT * FROM v_data_contratacao

--CRIANÇÃO DE VIEW COM DADOS DE VÁRIAS TABELAS USANDO UNION ALL
use curso
CREATE TABLE FORNECEDORES1
(ID_FORNEC INT PRIMARY KEY CHECK (ID_FORNEC BETWEEN 1 AND 150),
FORNEC CHAR(50)
)

CREATE TABLE FORNECEDORES2
(ID_FORNEC INT PRIMARY KEY CHECK (ID_FORNEC BETWEEN 151 AND 300),
FORNEC CHAR(50)
)

CREATE TABLE FORNECEDORES3
(ID_FORNEC INT PRIMARY KEY CHECK (ID_FORNEC BETWEEN 301 AND 450),
FORNEC CHAR(50)
)

CREATE TABLE FORNECEDORES4
(ID_FORNEC INT PRIMARY KEY CHECK (ID_FORNEC BETWEEN 451 AND 600),
FORNEC CHAR(50)
)

--INSERINDO DADOS
INSERT FORNECEDORES1 VALUES ('1', 'CaliforniaCorp')
INSERT FORNECEDORES1 VALUES ('5', 'BraziliaLtd')

INSERT FORNECEDORES2 VALUES ('231', 'FarEastt')
INSERT FORNECEDORES2 VALUES ('280', 'NZ')

INSERT FORNECEDORES3 VALUES ('321', 'EuroGroup')
INSERT FORNECEDORES3 VALUES ('442', 'UKArchip')

INSERT FORNECEDORES4 VALUES ('475', 'India')
INSERT FORNECEDORES4 VALUES ('521', 'Afrique')

--CRIANDO VIEW 
alter VIEW v_fornec_geral
as 
	SELECT 'f1'origem,id_fornec, fornec FROM FORNECEDORES1
	UNION ALL
	SELECT 'f2',id_fornec, fornec FROM FORNECEDORES2
	UNION ALL
	SELECT 'f3',id_fornec, fornec FROM FORNECEDORES3
	UNION ALL
	SELECT 'f4',id_fornec, fornec FROM FORNECEDORES4
	

-- SELECT NA VIEW v_fornec_geral
SELECT * FROM  v_fornec_geral





